# Generated by Django 5.2.16 on 2026-07-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                ("poster_image", models.ImageField(upload_to="posters/")),
                (
                    "casts",
                    models.ManyToManyField(related_name="%(class)s_set", to="api.cast"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="%(class)s_set", to="api.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                ("poster_image", models.ImageField(upload_to="posters/")),
                (
                    "casts",
                    models.ManyToManyField(related_name="%(class)s_set", to="api.cast"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="%(class)s_set", to="api.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
