# Generated by Django 6.0.6 on 2026-06-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("desc", models.TextField()),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Rating from 0.0 to 10.0",
                        max_digits=3,
                    ),
                ),
                ("views", models.IntegerField(default=0)),
            ],
        ),
    ]
